/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getProcessExists(processName: string): boolean
export const enum HkeyMap {
  HKCU = 0,
  HKLM = 1,
  HKCR = 2,
}
export const enum RegType {
  RegSz = 0,
  RegExpandSz = 1,
  RegMultiSz = 2,
  RegBinary = 3,
  RegDword = 4,
}
export function readRegistry(
  regKeyRoot: HkeyMap,
  regPath: string,
  regKeyName: string,
  regKeyValueType: RegType,
): unknown
export function writeRegistry(
  regKeyRoot: HkeyMap,
  regPath: string,
  regKeyName: string,
  regKeyValueType: RegType,
  regKeyValue: unknown,
): void
export function showWindowByTitle(windowTitle: string): void
